### ISSUE TITLE
the version of PyTorch

### ISSUE THREAD

**Issue by ShellingFord221** [kumar-shridhar/PyTorch-BayesianCNN#4]
Hi, I wonder which version of PyTorch you use. In the latest version (PyTorch 1.0), some settings occur errors. For example, AttributeError: module 'torch._C' has no attribute '_cuda_setDevice' (line: torch.cuda.set_device(0))

**Comment by kumar-shridhar** [comment]
I worked on PyTorch 0.4
